import { Site } from '../../../types/id-pass';

export const SITES_DATA: Site[] = [
  { id: 1, name: 'HIME CHANNEL', status: 'active' },
  { id: 2, name: 'KF京都風俗情報', status: 'active' },
  { id: 3, name: 'Qプリ', status: 'active' },
  { id: 4, name: 'オフィシャル(京都ホテヘル倶楽部様)', status: 'active' },
  { id: 5, name: 'ガールズヘブン', status: 'active' },
  { id: 6, name: 'シティヘブンネット', status: 'active' },
  { id: 7, name: 'ジョブヘブン【メンズヘブン】', status: 'active' },
  { id: 8, name: 'デリヘルタウン', status: 'active' },
  { id: 9, name: 'バニラ', status: 'active' },
  { id: 10, name: 'ぴゅあじょ', status: 'active' },
  { id: 11, name: 'ぴゅあらば', status: 'active' },
  { id: 12, name: 'ぴゅあらばスタッフ', status: 'active' },
  { id: 13, name: 'マンゾクネット', status: 'active' },
  { id: 14, name: '駅ちか人気！風俗ランキング', status: 'active' },
  { id: 15, name: '口コミ風俗情報局', status: 'active' },
  { id: 16, name: '風俗じゃぱん！', status: 'active' },
  { id: 17, name: 'デリヘルじゃぱん！', status: 'active' },
  { id: 18, name: 'フーコレ', status: 'active' },
  { id: 19, name: '出稼ぎちゃん', status: 'active' },
  { id: 20, name: '30からの風俗アルバイト【関西版】', status: 'active' },
  { id: 21, name: 'うれせん【関西・中四国版】', status: 'active' },
  { id: 22, name: 'ナイトピ', status: 'active' },
  { id: 23, name: 'Mr.Venrey【他アカウント】', status: 'active' },
];